image: python:3.8
definitions:
  steps:
    - step:
        name: Install dependencies
        script:
          - &install |
            python3 -m venv venv
            venv/bin/python -m pip install --upgrade pip setuptools wheel
            venv/bin/python -m pip install -r requirements-dev.txt
    - step:
        name: Run tests
        script:
          - &test |
            venv/bin/python -m pytest jsonlog 
pipelines:
  pull-requests:
    "staging":
      - step:
          caches:
            - pip
          deployment: Production
          name: Preview changes on staging->production
          script:
            - *install
            - *test
    "develop":
      - step:
          caches:
            - pip
          deployment: Staging
          name: Preview changes on develop->staging
          script:
            - *install
            - *test
    "**":
      - step:
          caches:
            - pip
          deployment: Testing 
          name: Preview changes on pull requests
          script:
            - *install
            - *test
  branches:
    feature/*:
      - step:
          caches:
            - pip
          name: test development
          deployment: Testing 
          script:
            - *install
            - *test
    bug/*:
      - step:
          caches:
            - pip
          name: test bugfix
          deployment: Testing 
          script:
            - *install
            - *test
    develop:
      - step:
          caches:
            - pip
          name: Deploy development
          deployment: Development
          script:
            - *install
            - *test
    staging:
      - step:
          caches:
            - pip
          name: Deploy staging
          deployment: Staging
          script:
            - *install
            - *test
    master:
      - step:
          caches:
            - pip
          name: Deploy production
          deployment: Production
          script:
            - *install
            - *test

